/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Procesos;

import InterfaceDocente.InicioDocente;
import InterfaceEstudiante.InicioEstudiante;
import javax.swing.JOptionPane;

/**
 *
 * @author IVÁN UTRIA
 */
public class CambiarClave extends javax.swing.JFrame {

    String documento;
    String tipo;
    ManejarClaves verificar;
    BuscarPersona buscar;
    
    public CambiarClave() {
        initComponents();
    }
    public CambiarClave(String documento, String tipo){
        initComponents();
        botonAtras.setVisible(false);
        this.documento=documento;
        this.tipo=tipo;
        verificar = new ManejarClaves();
        buscar = new BuscarPersona();
        textoClave.requestFocus();
        if(tipo.equals("ESTUDIANTE")){
            textoPersona.setText(buscar.buscarNombreEstudiante(documento));
        }
        else{
            textoPersona.setText(buscar.buscarNombreDocente(documento));
        }
    }
    public CambiarClave(String documento, String tipo, boolean iniciado){
        initComponents();
        botonAtras.setVisible(true);
        this.documento=documento;
        this.tipo=tipo;
        verificar = new ManejarClaves();
        buscar = new BuscarPersona();
        textoClave.requestFocus();
        if(tipo.equals("ESTUDIANTE")){
            textoPersona.setText(buscar.buscarNombreEstudiante(documento));
        }
        else{
            textoPersona.setText(buscar.buscarNombreDocente(documento));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textoPersona = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoConfirmacion = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoNuevaClave = new javax.swing.JPasswordField();
        textoClave = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COLEGIO PROGRAMARTE");
        getContentPane().setLayout(null);

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAceptar.png"))); // NOI18N
        botonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAceptar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonAceptarMouseMoved(evt);
            }
        });
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar);
        botonAceptar.setBounds(410, 330, 170, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 460, 260, 30);

        textoPersona.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoPersona.setForeground(new java.awt.Color(255, 255, 255));
        textoPersona.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(textoPersona);
        textoPersona.setBounds(620, 460, 160, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CAMBIAR CONTRASEÑA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 120, 240, 50);

        textoConfirmacion.setBackground(new java.awt.Color(0, 51, 102));
        textoConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        textoConfirmacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoConfirmacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoConfirmacionKeyPressed(evt);
            }
        });
        getContentPane().add(textoConfirmacion);
        textoConfirmacion.setBounds(360, 280, 220, 40);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CONFIRMAR NUEVA CLAVE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 280, 180, 40);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NUEVA CLAVE:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 230, 100, 40);

        textoNuevaClave.setBackground(new java.awt.Color(0, 51, 102));
        textoNuevaClave.setForeground(new java.awt.Color(255, 255, 255));
        textoNuevaClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        getContentPane().add(textoNuevaClave);
        textoNuevaClave.setBounds(360, 230, 220, 40);

        textoClave.setBackground(new java.awt.Color(0, 51, 102));
        textoClave.setForeground(new java.awt.Color(255, 255, 255));
        textoClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        getContentPane().add(textoClave);
        textoClave.setBounds(360, 180, 220, 40);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ACTUAL CLAVE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 180, 100, 40);

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png"))); // NOI18N
        botonAtras.setToolTipText("Atras");
        botonAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonAtrasMouseMoved(evt);
            }
        });
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        botonAtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botonAtrasKeyTyped(evt);
            }
        });
        getContentPane().add(botonAtras);
        botonAtras.setBounds(10, 10, 40, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="ACCIONES DE BOTONES">
    private void botonAceptarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseMoved
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAceptarDos.png")));
    }//GEN-LAST:event_botonAceptarMouseMoved

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAceptar.png")));
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png")));
    }//GEN-LAST:event_jLabel1MouseMoved

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        verificarNuevaClave();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textoConfirmacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoConfirmacionKeyPressed
        if(evt.getKeyCode() == 10){
            verificarNuevaClave();
        }
    }//GEN-LAST:event_textoConfirmacionKeyPressed

    private void botonAtrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseMoved
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtrasDos.png")));
    }//GEN-LAST:event_botonAtrasMouseMoved

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        terminar();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAtrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonAtrasKeyTyped

    }//GEN-LAST:event_botonAtrasKeyTyped
    // </editor-fold>
    
    private void verificarNuevaClave(){
        if(textoConfirmacion.getText().equals(textoNuevaClave.getText())){
            if(verificar.cambiarClave(documento,textoClave.getText(),textoConfirmacion.getText())){
                getToolkit().beep();
                JOptionPane.showMessageDialog(rootPane, "CLAVE CAMBIADA CORRECTAMENTE","EXITO",JOptionPane.INFORMATION_MESSAGE);
                terminar();
            }
            else{
                getToolkit().beep();
                JOptionPane.showMessageDialog(rootPane, "NO SE HA PODIDO CAMBIAR  LA CLAVE","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "VERIFIQUE QUE LA NUEVA CLAVE COINCIDA CON LA ESCRITA EN CONFIRMAR","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiar(){
        textoClave.setText("");
        textoNuevaClave.setText("");
        textoConfirmacion.setText("");
    }
    private void terminar(){
        if(tipo.equals("ESTUDIANTE")){
            InicioEstudiante mostrar = new InicioEstudiante(documento);
            mostrar.setVisible(true);
            this.dispose();
        }else{
            InicioDocente mostrar = new InicioDocente(documento);
            mostrar.setVisible(true);
            this.dispose();
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarClave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField textoClave;
    private javax.swing.JPasswordField textoConfirmacion;
    private javax.swing.JPasswordField textoNuevaClave;
    private javax.swing.JLabel textoPersona;
    // End of variables declaration//GEN-END:variables
}
