/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceAdministrator;

import Login.Colegio;
import javax.swing.JOptionPane;

/**
 *
 * @author IVÁN UTRIA
 */
public class MasOpciones extends javax.swing.JFrame {

    boolean panel;
    
    public MasOpciones(){
        initComponents();
        botonConfiguracion.setVisible(false);
        panelOpciones.setVisible(false);
        botonComboOcultar.setVisible(false);
        panel = false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        botonComboMostrar = new javax.swing.JButton();
        botonComboOcultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        iconoBotonLiquidacion = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        botonConfiguracion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        iconoMostrarRegistro = new javax.swing.JLabel();
        botonMostrarRegistro = new javax.swing.JButton();
        iconoBotonRestaurar = new javax.swing.JLabel();
        botonRestaurar = new javax.swing.JButton();
        botonLiquidacion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COLEGIO PROGRAMARTE");
        getContentPane().setLayout(null);

        botonComboMostrar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonComboMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/combo2.png"))); // NOI18N
        botonComboMostrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonComboMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonComboMostrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                botonComboMostrarMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonComboMostrarMouseMoved(evt);
            }
        });
        botonComboMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonComboMostrarMouseClicked(evt);
            }
        });
        getContentPane().add(botonComboMostrar);
        botonComboMostrar.setBounds(690, 20, 30, 30);

        botonComboOcultar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonComboOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/combo3.png"))); // NOI18N
        botonComboOcultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonComboOcultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonComboOcultar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                botonComboOcultarMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonComboOcultarMouseMoved(evt);
            }
        });
        botonComboOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonComboOcultarMouseClicked(evt);
            }
        });
        getContentPane().add(botonComboOcultar);
        botonComboOcultar.setBounds(690, 20, 30, 30);

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seleccione.png"))); // NOI18N
        jLabel2.setText("  SELECCIONE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 20, 140, 30);

        iconoBotonLiquidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoLiquidacion.png"))); // NOI18N
        iconoBotonLiquidacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoBotonLiquidacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iconoBotonLiquidacionMouseMoved(evt);
            }
        });
        iconoBotonLiquidacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoBotonLiquidacionMouseClicked(evt);
            }
        });
        getContentPane().add(iconoBotonLiquidacion);
        iconoBotonLiquidacion.setBounds(570, 170, 120, 130);

        panelOpciones.setBackground(new java.awt.Color(0, 51, 102));
        panelOpciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelOpcionesMouseMoved(evt);
            }
        });
        panelOpciones.setLayout(null);

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        botonSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonSalirMouseMoved(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panelOpciones.add(botonSalir);
        botonSalir.setBounds(0, 20, 160, 30);

        botonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        botonConfiguracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConfiguracion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonConfiguracionMouseMoved(evt);
            }
        });
        botonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfiguracionActionPerformed(evt);
            }
        });
        panelOpciones.add(botonConfiguracion);
        botonConfiguracion.setBounds(0, 20, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        panelOpciones.add(jLabel1);
        jLabel1.setBounds(0, 10, 34, 14);

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonSalirDos.png"))); // NOI18N
        botonCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonCerrarMouseMoved(evt);
            }
        });
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        panelOpciones.add(botonCerrar);
        botonCerrar.setBounds(0, 60, 160, 30);

        getContentPane().add(panelOpciones);
        panelOpciones.setBounds(560, 50, 160, 90);

        iconoMostrarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoRegistrar.png"))); // NOI18N
        iconoMostrarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoMostrarRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iconoMostrarRegistroMouseMoved(evt);
            }
        });
        iconoMostrarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoMostrarRegistroMouseClicked(evt);
            }
        });
        getContentPane().add(iconoMostrarRegistro);
        iconoMostrarRegistro.setBounds(130, 170, 120, 130);

        botonMostrarRegistro.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        botonMostrarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonVerRegistro.png"))); // NOI18N
        botonMostrarRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonMostrarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMostrarRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonMostrarRegistroMouseMoved(evt);
            }
        });
        botonMostrarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrarRegistro);
        botonMostrarRegistro.setBounds(100, 310, 170, 40);

        iconoBotonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoRestaurarClave.png"))); // NOI18N
        iconoBotonRestaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoBotonRestaurar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iconoBotonRestaurarMouseMoved(evt);
            }
        });
        iconoBotonRestaurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoBotonRestaurarMouseClicked(evt);
            }
        });
        getContentPane().add(iconoBotonRestaurar);
        iconoBotonRestaurar.setBounds(350, 170, 120, 130);

        botonRestaurar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        botonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonRestaurarClave.png"))); // NOI18N
        botonRestaurar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonRestaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRestaurar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonRestaurarMouseMoved(evt);
            }
        });
        botonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaurarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRestaurar);
        botonRestaurar.setBounds(320, 310, 170, 40);

        botonLiquidacion.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        botonLiquidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonLiquidacionDocente.png"))); // NOI18N
        botonLiquidacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonLiquidacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLiquidacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonLiquidacionMouseMoved(evt);
            }
        });
        botonLiquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLiquidacionActionPerformed(evt);
            }
        });
        getContentPane().add(botonLiquidacion);
        botonLiquidacion.setBounds(540, 310, 170, 40);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ADMINISTRADOR");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 460, 200, 30);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoUsuario.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(730, 10, 60, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 460, 170, 30);

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png"))); // NOI18N
        botonAtras.setToolTipText("Atras");
        botonAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonAtrasMouseMoved(evt);
            }
        });
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        botonAtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botonAtrasKeyTyped(evt);
            }
        });
        getContentPane().add(botonAtras);
        botonAtras.setBounds(10, 10, 40, 39);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INICIO / MAS OPCIONES");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 430, 780, 14);

        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png"))); // NOI18N
        BotonInicio.setToolTipText("Regresar al Inico");
        BotonInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonInicioMouseMoved(evt);
            }
        });
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInicio);
        BotonInicio.setBounds(60, 10, 43, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonComboMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComboMostrarMouseClicked
        panelOpciones.setVisible(true);
        botonComboMostrar.setVisible(false);
        botonComboOcultar.setVisible(true);

    }//GEN-LAST:event_botonComboMostrarMouseClicked

    private void botonComboMostrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComboMostrarMouseMoved
        botonComboMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/combo4.png")));
    }//GEN-LAST:event_botonComboMostrarMouseMoved

    private void botonComboMostrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComboMostrarMouseDragged
    }//GEN-LAST:event_botonComboMostrarMouseDragged
    
    private void botonComboOcultarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComboOcultarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComboOcultarMouseDragged

    private void botonComboOcultarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComboOcultarMouseMoved
        botonComboOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/combo5.png")));
    }//GEN-LAST:event_botonComboOcultarMouseMoved

    private void botonComboOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComboOcultarMouseClicked
        panelOpciones.setVisible(false);
        botonComboMostrar.setVisible(true);
        botonComboOcultar.setVisible(false);
    }//GEN-LAST:event_botonComboOcultarMouseClicked

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        salir();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonMostrarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarRegistroActionPerformed
        RestaurarClave mostrar = new RestaurarClave(true);
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonMostrarRegistroActionPerformed

    private void botonLiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLiquidacionActionPerformed
        RegistrarLiquidacion mostrar = new RegistrarLiquidacion();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonLiquidacionActionPerformed

    private void botonMostrarRegistroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMostrarRegistroMouseMoved
        botonMostrarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonVerRegistroDos.png")));
    }//GEN-LAST:event_botonMostrarRegistroMouseMoved

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        mostrarOcultar();
    }//GEN-LAST:event_jLabel3MouseMoved

    private void mostrarOcultar(){
        if(panel==true)
        {
            panelOpciones.setVisible(false);
            botonComboMostrar.setVisible(true);
            botonComboOcultar.setVisible(false);
        }
        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonSalirDos.png")));
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png")));
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png")));
        botonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonRestaurarClave.png")));
        botonMostrarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonVerRegistro.png")));
        botonLiquidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonLiquidacionDocente.png")));
        botonComboMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/combo2.png")));
        iconoMostrarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoRegistrar.png")));
        botonComboOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/combo3.png")));
        botonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png")));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png")));
        iconoBotonLiquidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoLiquidacion.png")));
        iconoBotonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoRestaurarClave.png")));
    }
    
    private void botonLiquidacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLiquidacionMouseMoved
        botonLiquidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonLiquidacionDocenteDos.png")));
    }//GEN-LAST:event_botonLiquidacionMouseMoved

    private void botonConfiguracionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConfiguracionMouseMoved
        botonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracionDos.png")));
    }//GEN-LAST:event_botonConfiguracionMouseMoved

    private void iconoMostrarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoMostrarRegistroMouseClicked
        RestaurarClave mostrar = new RestaurarClave(true);
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_iconoMostrarRegistroMouseClicked

    private void iconoBotonLiquidacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoBotonLiquidacionMouseClicked
        RegistrarLiquidacion mostrar = new RegistrarLiquidacion();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_iconoBotonLiquidacionMouseClicked

    private void iconoMostrarRegistroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoMostrarRegistroMouseMoved
        iconoMostrarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoRegistrarDos.png")));
    }//GEN-LAST:event_iconoMostrarRegistroMouseMoved

    private void botonSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseMoved
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirDos.png")));
    }//GEN-LAST:event_botonSalirMouseMoved

    private void iconoBotonLiquidacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoBotonLiquidacionMouseMoved
        iconoBotonLiquidacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoLiquidacionDos.png")));
    }//GEN-LAST:event_iconoBotonLiquidacionMouseMoved

    private void panelOpcionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpcionesMouseMoved
        panelOpciones.setVisible(true);
        panel=true;
        botonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png")));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png")));
        botonComboOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/combo3.png")));
    }//GEN-LAST:event_panelOpcionesMouseMoved

    private void botonRestaurarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRestaurarMouseMoved
        botonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonRestaurarClaveDos.png")));
    }//GEN-LAST:event_botonRestaurarMouseMoved

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        evt = null;
    }//GEN-LAST:event_jLabel2MouseMoved

    private void botonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfiguracionActionPerformed
        JOptionPane.showMessageDialog(null, "EN CONSTRUCCIÓN");
    }//GEN-LAST:event_botonConfiguracionActionPerformed

    private void botonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarActionPerformed
        RestaurarClave mostrar = new RestaurarClave();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRestaurarActionPerformed

    private void iconoBotonRestaurarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoBotonRestaurarMouseMoved
        iconoBotonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoRestaurarClaveDos.png")));
    }//GEN-LAST:event_iconoBotonRestaurarMouseMoved

    private void iconoBotonRestaurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoBotonRestaurarMouseClicked
        RestaurarClave mostrar = new RestaurarClave();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_iconoBotonRestaurarMouseClicked

    private void botonAtrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseMoved
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtrasDos.png")));
    }//GEN-LAST:event_botonAtrasMouseMoved

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        Administrador mostrar = new Administrador();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAtrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonAtrasKeyTyped

    }//GEN-LAST:event_botonAtrasKeyTyped

    private void BotonInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseMoved
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicioDos.png")));
    }//GEN-LAST:event_BotonInicioMouseMoved

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        Administrador mostrar = new Administrador();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonInicioActionPerformed

    private void botonCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseMoved
        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonSalir.png")));
    }//GEN-LAST:event_botonCerrarMouseMoved

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        int seleccion = JOptionPane.showConfirmDialog(null, "¿SEGURO QUE DESEA CERRAR EL PROGRAMA?");
        if(JOptionPane.OK_OPTION == seleccion){
            System.exit(0);
        }
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void mostrarEstudiante(){
        RegistrarPersona mostrar = new RegistrarPersona("ESTUDIANTE");
        mostrar.setVisible(true);
        this.dispose();
    }
    private void salir(){
        Colegio mostrar = new Colegio();
        mostrar.setVisible(true);
        this.dispose();
    }
    private void mensaje(){
        
        getToolkit().beep();
        JOptionPane.showMessageDialog(rootPane, "ESTA OPCIÓN SE ENCUENTRA EN CONSTRUCCION, INTENTE MAS TARDE", "EN CONSTRUCCIÓN", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonComboMostrar;
    private javax.swing.JButton botonComboOcultar;
    private javax.swing.JButton botonConfiguracion;
    private javax.swing.JButton botonLiquidacion;
    private javax.swing.JButton botonMostrarRegistro;
    private javax.swing.JButton botonRestaurar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel iconoBotonLiquidacion;
    private javax.swing.JLabel iconoBotonRestaurar;
    private javax.swing.JLabel iconoMostrarRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables
}
