
package InterfaceAdministrator;

import Datos.*;
import Procesos.*;
import javax.swing.JOptionPane;

public class ModificarDatos extends javax.swing.JFrame {

    boolean panel;
    Usuarios usuarios;
    String tipo;
    String documento;
    EditarDatos editar;
    public ModificarDatos() {
        initComponents();
    }
    public ModificarDatos(String tipo, String documento) {
        initComponents();
        
        editar = new EditarDatos();
        
        if(tipo.equals("DOCENTE")){
            editar.buscarDocente(documento);
            textoTipo.setText("ASIGNATURA:");
            textoTitulo.setText("MODIFICAR DATOS DE DOCENTE");
            textoUrl.setText("INICIO / REGISTRAR PERSONA / REGISTRAR DOCENTE / DOCENTES REGISTRADOS / MODIFICAR DATOS");
            llenarComboTipoDocente();
        }
        else{
            editar.buscarEstudiante(documento);
            textoTitulo.setText("MODIFICAR DATOS DE ESTUDIANTE");
            textoUrl.setText("INICIO / REGISTRAR PERSONA / REGISTRAR ESTUDIANTES / ESTUDIANTES REGISTRADOS / MODIFICAR DATOS");
            textoTipo.setText("GRADO:");
            llenarComboTipoEstudiante();
        }
        
        this.tipo = tipo;
        this.documento = documento;
        llenarCombos();
        panel=false;
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textoDireccion = new javax.swing.JTextField();
        textoDocumento = new javax.swing.JTextField();
        textoNombre = new javax.swing.JTextField();
        comboSexo = new javax.swing.JComboBox<>();
        textoTelefono = new javax.swing.JTextField();
        comboYear = new javax.swing.JComboBox<>();
        comboDia = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textoTipo = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        textoMateria = new javax.swing.JLabel();
        textoUrl = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JButton();
        textoTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COLEGIO PROGRAMARTE");
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ADMINISTRADOR");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 460, 200, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 460, 260, 30);

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCancelar.png"))); // NOI18N
        botonCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonCancelarMouseMoved(evt);
            }
        });
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar);
        botonCancelar.setBounds(600, 350, 170, 39);

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardar.png"))); // NOI18N
        botonGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonGuardarMouseMoved(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(600, 290, 170, 39);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        textoDireccion.setBackground(new java.awt.Color(0, 51, 102));
        textoDireccion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoDireccion.setForeground(new java.awt.Color(255, 255, 255));
        textoDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(textoDireccion);
        textoDireccion.setBounds(200, 200, 230, 40);

        textoDocumento.setEditable(false);
        textoDocumento.setBackground(new java.awt.Color(0, 51, 102));
        textoDocumento.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoDocumento.setForeground(new java.awt.Color(255, 255, 255));
        textoDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoDocumentoKeyTyped(evt);
            }
        });
        jPanel1.add(textoDocumento);
        textoDocumento.setBounds(200, 50, 230, 40);

        textoNombre.setBackground(new java.awt.Color(0, 51, 102));
        textoNombre.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNombreKeyTyped(evt);
            }
        });
        jPanel1.add(textoNombre);
        textoNombre.setBounds(200, 100, 230, 40);

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "MASCULINO", "FEMENINO" }));
        jPanel1.add(comboSexo);
        comboSexo.setBounds(200, 250, 230, 30);

        textoTelefono.setBackground(new java.awt.Color(0, 51, 102));
        textoTelefono.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        textoTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(textoTelefono);
        textoTelefono.setBounds(200, 150, 230, 40);

        comboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYearActionPerformed(evt);
            }
        });
        jPanel1.add(comboYear);
        comboYear.setBounds(200, 290, 90, 30);

        jPanel1.add(comboDia);
        comboDia.setBounds(370, 290, 60, 30);

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT", "NOV", "DIC" }));
        comboMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMesItemStateChanged(evt);
            }
        });
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });
        jPanel1.add(comboMes);
        comboMes.setBounds(300, 290, 60, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("FECHA DE NACIMIENTO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 290, 170, 20);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DOCUMENTO: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 60, 110, 20);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("NOMBRE:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 110, 110, 20);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("TELEFONO:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 160, 110, 20);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("DIRECCIÓN:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 210, 110, 20);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("SEXO:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 250, 110, 20);

        textoTipo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoTipo.setForeground(new java.awt.Color(255, 255, 255));
        textoTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoTipo.setText("- - - - - - - - - - - - -");
        jPanel1.add(textoTipo);
        textoTipo.setBounds(70, 4, 110, 30);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        jPanel1.add(comboTipo);
        comboTipo.setBounds(200, 10, 230, 30);

        textoMateria.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoMateria.setForeground(new java.awt.Color(255, 255, 255));
        textoMateria.setText("jLabel1");
        textoMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.add(textoMateria);
        textoMateria.setBounds(200, 0, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 70, 450, 340);

        textoUrl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        textoUrl.setForeground(new java.awt.Color(255, 255, 255));
        textoUrl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoUrl.setText("---");
        getContentPane().add(textoUrl);
        textoUrl.setBounds(10, 430, 780, 14);

        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png"))); // NOI18N
        BotonInicio.setToolTipText("Regresar al Inico");
        BotonInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonInicioMouseMoved(evt);
            }
        });
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInicio);
        BotonInicio.setBounds(10, 10, 43, 40);

        textoTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoTitulo.setText("-------");
        getContentPane().add(textoTitulo);
        textoTitulo.setBounds(330, 10, 460, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   // <editor-fold defaultstate="collapsed" desc="ACCION DE BOTONES">
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        terminar();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        modificar();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed
        
    }//GEN-LAST:event_comboMesActionPerformed

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCancelar.png")));
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png")));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardar.png")));
    }//GEN-LAST:event_jLabel3MouseMoved

    private void comboMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMesItemStateChanged
        
    }//GEN-LAST:event_comboMesItemStateChanged

    private void botonGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseMoved
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardarDos.png")));
    }//GEN-LAST:event_botonGuardarMouseMoved

    private void botonCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseMoved
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCancelarDos.png")));
    }//GEN-LAST:event_botonCancelarMouseMoved

    private void textoDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDocumentoKeyTyped
        impedirNumeros(evt);
    }//GEN-LAST:event_textoDocumentoKeyTyped

    private void textoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTelefonoKeyTyped
        impedirNumeros(evt);
    }//GEN-LAST:event_textoTelefonoKeyTyped

    private void comboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearActionPerformed
        
    }//GEN-LAST:event_comboYearActionPerformed

    private void textoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombreKeyTyped
        char validar = evt.getKeyChar();
        if(validar>=48 && validar <=57){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textoNombreKeyTyped

    private void BotonInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseMoved
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicioDos.png")));
    }//GEN-LAST:event_BotonInicioMouseMoved

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        Administrador mostrar = new Administrador();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonInicioActionPerformed

    private void impedirNumeros(java.awt.event.KeyEvent evt){
        char validar = evt.getKeyChar();
        if(validar!=48 && validar!=49 && validar!=50 
        && validar!=51 && validar!=52 && validar!=53
        && validar!=54 && validar!=55
        && validar!=56 && validar!=57
        && validar!=127 && validar!=8)
        {
            getToolkit().beep();
            evt.consume();
        }
        
    }
    // </editor-fold> 
    
    private void cargarDatos(){
        comboMes.setSelectedItem(editar.getMesNacimiento());
        comboDia.setSelectedItem(editar.getDiaNacimiento());
        textoDocumento.setText(documento);
        textoNombre.setText(editar.getNombre());
        if(tipo.equals("ESTUDIANTE")){
            textoMateria.setVisible(false);
            comboTipo.setSelectedItem(editar.getGrado());
        }else{
            textoMateria.setVisible(true);
            textoMateria.setText(editar.getMateria());
            comboTipo.setVisible(false);
        }
        textoDireccion.setText(editar.getDireccion());
        textoTelefono.setText(editar.getTelefono());
        comboSexo.setSelectedItem(editar.getSexo());
        comboYear.setSelectedItem(editar.getYearNacimiento());
    }
    private void modificar(){
        if(verificarCampos()==true){
            String nombre = textoNombre.getText().toUpperCase();
            String telefono = textoTelefono.getText();
            String direccion = textoDireccion.getText().toUpperCase();
            String sexo = comboSexo.getSelectedItem().toString();
            String year = comboYear.getSelectedItem().toString();
            String mes = comboMes.getSelectedItem().toString();
            String dia = comboDia.getSelectedItem().toString();
            String grado = comboTipo.getSelectedItem().toString();
            String materia = comboTipo.getSelectedItem().toString();
            if(tipo.equals("DOCENTE")){
                new ModificarDatosPersona().modificarDatosDocente(documento, nombre,telefono,direccion,sexo,year,mes,dia,materia);
                getToolkit().beep();
                JOptionPane.showMessageDialog(rootPane, "SE HAN CAMBIADO LOS DATOS");
                terminar();
            }else{
                new ModificarDatosPersona().modificarDatosEstudiante(documento, nombre,telefono,direccion,sexo,year,mes,dia,grado);
                getToolkit().beep();
                JOptionPane.showMessageDialog(rootPane, "SE HAN CAMBIADO LOS DATOS");
                terminar();
            }   

        }else{
            JOptionPane.showMessageDialog(rootPane, "VERIFIQUE QUE LOS DATOS ESTEN CORRECTOS");
        }
    }
    private boolean verificarCampos(){
        if(tipo.equals("ESTUDIANTE")){
            if(textoNombre.getText().trim().equals("") 
            || textoTelefono.getText().trim().equals("")
            || textoDireccion.getText().trim().equals("")
            || comboSexo.getSelectedItem().toString().trim().equals("SELECCIONE")
            || comboTipo.getSelectedItem().toString().trim().equals("SELECCIONE")
            || comboDia.getSelectedItem().toString().trim().equals("DD")
            || comboMes.getSelectedItem().toString().trim().equals("MM")
            || comboYear.getSelectedItem().toString().trim().equals("AAAA")){
                return false;
            }
            else{
                return true;
            }
        }else{
            if(textoNombre.getText().trim().equals("") 
            || textoTelefono.getText().trim().equals("")
            || textoDireccion.getText().trim().equals("")
            || comboSexo.getSelectedItem().toString().trim().equals("SELECCIONE")
            || comboDia.getSelectedItem().toString().trim().equals("DD")
            || comboMes.getSelectedItem().toString().trim().equals("MM")
            || comboYear.getSelectedItem().toString().trim().equals("AAAA")){
                return false;
            }
            else{
                return true;
            }
        }
    }
    
    private void limpiar(){
        textoNombre.setText("");
        textoDocumento.setText("");
        textoTelefono.setText("");
        textoDireccion.setText("");
        comboTipo.setSelectedItem("SELECCIONE");
        comboDia.setSelectedItem("DD");
        comboMes.setSelectedItem("MM");
        comboYear.setSelectedItem("AAAA");
        comboSexo.setSelectedItem("SELECCIONE");
    }
    
    private void llenarCombos(){
        comboYear.addItem("AAAA");
        comboDia.addItem("DD");
        
        for(int i = 2018; i>=1938;i--){
            comboYear.addItem(""+i);
        }
        for(int i = 1; i<=31;i++){
            comboDia.addItem(""+i);
        }
    }
    private void llenarComboTipoDocente(){
        comboTipo.addItem("ESPAÑOL"); 
        comboTipo.addItem("MATEMATICAS");
        comboTipo.addItem("SOCIALES");
        comboTipo.addItem("INFORMATICA");
        comboTipo.addItem("NATURALES");
        comboTipo.addItem("ARTISTICA");
        comboTipo.addItem("DEPORTE");
    }
    private void llenarComboTipoEstudiante(){
        for (int i = 6; i <= 11; i++) {
            comboTipo.addItem(""+i);
        }
    }
    private void terminar(){
        
        new MostrarPersona(tipo).setVisible(true);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoDocumento;
    private javax.swing.JLabel textoMateria;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    private javax.swing.JLabel textoTipo;
    private javax.swing.JLabel textoTitulo;
    private javax.swing.JLabel textoUrl;
    // End of variables declaration//GEN-END:variables
}
