
package InterfaceAdministrator;

import Procesos.*;
import javax.swing.JOptionPane;

public class MostrarPersona extends javax.swing.JFrame {

    String tipo;
    

    public MostrarPersona(){
        initComponents();
    }
    public MostrarPersona(String tipo){
        this.tipo=tipo;
        initComponents();
        if(tipo.equals("DOCENTE")){
            textoTitulo.setText("DOCENTES REGISTRADOS");
            textoUrl.setText("INICIO / REGISTRAR PERSONA / REGISTRAR DOCENTE / DOCENTES REGISTRADOS");
            textoNombre.setVisible(false);
            textoFiltro.setVisible(false);
            tabla.setModel(new CargarTabla().tablaDocentes());
        }else{
            textoTitulo.setText("ESTUDIANTES REGISTRADOS");
            textoUrl.setText("INICIO / REGISTRAR PERSONA / REGISTRAR ESTUDIANTES / ESTUDIANTES REGISTRADOS");
            textoNombre.setVisible(true);
            textoFiltro.setVisible(true);
            tabla.setModel(new CargarTabla().tablaEstudiantes());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        BotonInicio = new javax.swing.JButton();
        textoNombre = new javax.swing.JTextField();
        textoFiltro = new javax.swing.JLabel();
        textoUrl = new javax.swing.JLabel();
        textoTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INICIO / VER NOTAS DE ESTUDIANTE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COLEGIO PROGRAMARTE");
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ADMINISTRADOR");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 460, 200, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 460, 260, 30);

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png"))); // NOI18N
        botonAtras.setToolTipText("Atras");
        botonAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonAtrasMouseMoved(evt);
            }
        });
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras);
        botonAtras.setBounds(10, 10, 40, 40);

        tabla = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        tabla.setBackground(new java.awt.Color(0, 51, 102));
        tabla.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tabla.setForeground(new java.awt.Color(255, 255, 255));
        tabla.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 780, 210);

        botonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonEliminar.png"))); // NOI18N
        botonEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonEliminarMouseMoved(evt);
            }
        });
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar);
        botonEliminar.setBounds(620, 370, 170, 40);

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonEditar.png"))); // NOI18N
        botonEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonEditarMouseMoved(evt);
            }
        });
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEditar);
        botonEditar.setBounds(440, 370, 170, 40);

        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png"))); // NOI18N
        BotonInicio.setToolTipText("Regresar al Inico");
        BotonInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonInicioMouseMoved(evt);
            }
        });
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInicio);
        BotonInicio.setBounds(60, 10, 43, 40);

        textoNombre.setBackground(new java.awt.Color(0, 51, 102));
        textoNombre.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNombreKeyTyped(evt);
            }
        });
        getContentPane().add(textoNombre);
        textoNombre.setBounds(310, 90, 310, 40);

        textoFiltro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoFiltro.setForeground(new java.awt.Color(255, 255, 255));
        textoFiltro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoFiltro.setText("FILTRAR POR NOMBRE:");
        getContentPane().add(textoFiltro);
        textoFiltro.setBounds(140, 90, 160, 40);

        textoUrl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        textoUrl.setForeground(new java.awt.Color(255, 255, 255));
        textoUrl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoUrl.setText("----");
        getContentPane().add(textoUrl);
        textoUrl.setBounds(10, 430, 780, 14);

        textoTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoTitulo.setText("-------");
        getContentPane().add(textoTitulo);
        textoTitulo.setBounds(490, 10, 300, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // <editor-fold defaultstate="collapsed" desc="Accion de Botones">  
    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        if(tipo.equals("DOCENTE")){
            RegistrarPersona admin = new RegistrarPersona("DOCENTE");
            admin.setVisible(true);
            this.dispose();
        }else{
            RegistrarPersona admin = new RegistrarPersona("ESTUDIANTE");
            admin.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png")));
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png")));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonEliminar.png")));
        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonEditar.png")));
    }//GEN-LAST:event_jLabel3MouseMoved

    private void botonAtrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseMoved
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtrasDos.png")));
    }//GEN-LAST:event_botonAtrasMouseMoved

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int seleccion = JOptionPane.showConfirmDialog(null, "¿SEGURO QUE DESEA ELIMINAR ESTA PERSONA DEL REGISTRO?");
        if(JOptionPane.OK_OPTION == seleccion){
            eliminar();
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonEliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseMoved
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonEliminarDos.png")));
    }//GEN-LAST:event_botonEliminarMouseMoved

    private void botonEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseMoved
        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonEditarDos.png")));
    }//GEN-LAST:event_botonEditarMouseMoved

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        accionBotonEditar();
    }//GEN-LAST:event_botonEditarActionPerformed

    private void BotonInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseMoved
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicioDos.png")));
    }//GEN-LAST:event_BotonInicioMouseMoved

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        Administrador mostrar = new Administrador();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonInicioActionPerformed

    private void textoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombreKeyTyped
        filtro();
    }//GEN-LAST:event_textoNombreKeyTyped
    
    private void error(){
        getToolkit().beep();
        JOptionPane.showMessageDialog(rootPane, "DEBE SELECCIONAR LA PERONA QUE DESEA ELIMINAR DE LA LISTA","ACCIÓN INVALIDA",JOptionPane.ERROR_MESSAGE);
    }
    // </editor-fold>
    
    private void filtro(){
        if(textoNombre.getText().trim().equals("")){
            tabla.setModel(new CargarTabla().tablaEstudiantes());
        }else{
            tabla.setModel(new CargarTabla().filtrarNombre(textoNombre.getText()));
        }
    }
    
    private void accionBotonEditar(){
        try{
        String documento = (String) tabla.getValueAt(tabla.getSelectedRow(), 1);
        ModificarDatos mostrar = new ModificarDatos(tipo, documento);
        mostrar.setVisible(true);
        this.dispose();
        }catch(Exception e){
            getToolkit().beep();
        JOptionPane.showMessageDialog(rootPane, "DEBE SELECCIONAR UNA PERSONA PARA PODER EDITAR SUS DATOS","ACCIÓN INVALIDA",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void eliminar(){
        EliminarUsuarios eliminar = new EliminarUsuarios();
        String documento = (String) tabla.getValueAt(tabla.getSelectedRow(), 1);
        if(tipo=="DOCENTE"){
            if(eliminar.eliminarListaDocente(documento)){
                if(eliminar.eliminarPersonaListaUsuario(documento)){
                    if(eliminar.eliminarMateriaDocente(documento)){
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(rootPane, "SE HA ELIMINADO EL USUARIO CON EXITO","EXITO",JOptionPane.INFORMATION_MESSAGE);
                        tabla.setModel(new CargarTabla().tablaDocentes());
                    }
                }
            }
        }else{
            if(eliminar.eliminarListaEstudiante(documento)){
                if(eliminar.eliminarPersonaListaUsuario(documento)){
                    if(eliminar.eliminarEstudianteListaNotas(documento)){
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(rootPane, "SE HA ELIMINADO EL USUARIO CON EXITO","EXITO",JOptionPane.INFORMATION_MESSAGE);
                        filtro();
                    }
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel textoFiltro;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JLabel textoTitulo;
    private javax.swing.JLabel textoUrl;
    // End of variables declaration//GEN-END:variables
}
