/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDocente;

import Datos.*;
import Datos.Estudiante;
import Procesos.ActualizarDatos;
import Procesos.BuscarPersona;
import Procesos.ManejarArchivos;
import Procesos.MostrarNotas;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IVÁN UTRIA
 */
public class EditarNotas extends javax.swing.JFrame {

    ActualizarDatos cambiarNotas;
    String documentoDocente;
    String documento;
    float notaUno=0;
    float notaDos=0;
    float notaTres=0;
    
    public EditarNotas(){
        initComponents();
    }
    public EditarNotas(String documento, String documentoDocente){
        initComponents();
        cambiarNotas = new ActualizarDatos();
        cambiarNotas.buscarNotasEstudiante(documento, documentoDocente);
        this.documento=documento;
        textoMateria.setText(new BuscarPersona().buscarNombreMateria(documentoDocente));
        this.documentoDocente = documentoDocente;
        llenar();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        textoMateria = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoNotaTres = new javax.swing.JTextField();
        textoNotaUno = new javax.swing.JTextField();
        textoNotaDos = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoObservaciones = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoTitulo = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COLEGIO PROGRAMARTE");
        getContentPane().setLayout(null);

        textoMateria.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        textoMateria.setForeground(new java.awt.Color(255, 255, 255));
        textoMateria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoMateria.setText("------");
        getContentPane().add(textoMateria);
        textoMateria.setBounds(580, 460, 200, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 460, 260, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOTA3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 170, 100, 20);

        textoNotaTres.setBackground(new java.awt.Color(0, 51, 102));
        textoNotaTres.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoNotaTres.setForeground(new java.awt.Color(255, 255, 255));
        textoNotaTres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNotaTres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoNotaTres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNotaTresKeyTyped(evt);
            }
        });
        getContentPane().add(textoNotaTres);
        textoNotaTres.setBounds(470, 130, 100, 40);

        textoNotaUno.setBackground(new java.awt.Color(0, 51, 102));
        textoNotaUno.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoNotaUno.setForeground(new java.awt.Color(255, 255, 255));
        textoNotaUno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNotaUno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoNotaUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNotaUnoKeyTyped(evt);
            }
        });
        getContentPane().add(textoNotaUno);
        textoNotaUno.setBounds(220, 130, 100, 40);

        textoNotaDos.setBackground(new java.awt.Color(0, 51, 102));
        textoNotaDos.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoNotaDos.setForeground(new java.awt.Color(255, 255, 255));
        textoNotaDos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNotaDos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoNotaDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNotaDosKeyTyped(evt);
            }
        });
        getContentPane().add(textoNotaDos);
        textoNotaDos.setBounds(350, 130, 100, 40);

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardar.png"))); // NOI18N
        botonGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonGuardarMouseMoved(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(220, 350, 170, 40);

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCancelar.png"))); // NOI18N
        botonCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonCancelarMouseMoved(evt);
            }
        });
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar);
        botonCancelar.setBounds(400, 350, 170, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOTA1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 170, 90, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("OBSERVACIONES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 320, 350, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NOTA2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 170, 100, 20);

        textoObservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));
        textoObservaciones.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoObservaciones.setForeground(new java.awt.Color(0, 51, 102));
        textoObservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoObservacionesKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(textoObservaciones);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 190, 350, 130);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INICIO / REGISTRAR NOTAS / EDITAR NOTAS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 430, 780, 14);

        textoNombre.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(255, 255, 255));
        textoNombre.setText("---");
        textoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        getContentPane().add(textoNombre);
        textoNombre.setBounds(220, 80, 350, 40);

        textoTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoTitulo.setText("EDITAR NOTAS");
        getContentPane().add(textoTitulo);
        textoTitulo.setBounds(490, 10, 300, 40);

        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png"))); // NOI18N
        BotonInicio.setToolTipText("Regresar al Inico");
        BotonInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonInicioMouseMoved(evt);
            }
        });
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInicio);
        BotonInicio.setBounds(10, 10, 43, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardar.png")));
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png")));
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCancelar.png")));
    }//GEN-LAST:event_jLabel3MouseMoved

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textoNotaUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNotaUnoKeyTyped
        if(textoNotaUno.getText().equals("") && evt.getKeyChar()==46){
            getToolkit().beep();
            evt.consume();
        }
        impedirNumeros(evt);
    }//GEN-LAST:event_textoNotaUnoKeyTyped

    private void textoNotaDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNotaDosKeyTyped
        if(textoNotaDos.getText().equals("") && evt.getKeyChar()==46){
            getToolkit().beep();
            evt.consume();
        }
        impedirNumeros(evt);
    }//GEN-LAST:event_textoNotaDosKeyTyped

    private void textoNotaTresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNotaTresKeyTyped
        if(textoNotaTres.getText().equals("") && evt.getKeyChar()==46){
            getToolkit().beep();
            evt.consume();
        }
        impedirNumeros(evt);
    }//GEN-LAST:event_textoNotaTresKeyTyped

    private void textoObservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoObservacionesKeyTyped
    }//GEN-LAST:event_textoObservacionesKeyTyped

    private void botonGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseMoved
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonGuardarDos.png")));
    }//GEN-LAST:event_botonGuardarMouseMoved

    private void botonCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseMoved
       botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCancelarDos.png")));
    }//GEN-LAST:event_botonCancelarMouseMoved

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        new MostrarNotasRegistradas(documentoDocente).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void BotonInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseMoved
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicioDos.png")));
    }//GEN-LAST:event_BotonInicioMouseMoved

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        new InicioDocente(documentoDocente).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonInicioActionPerformed
    private void impedirNumeros(java.awt.event.KeyEvent evt){
        char validar = evt.getKeyChar();
        
        if(validar!=48 && validar!=49 && validar!=50 
        && validar!=51 && validar!=52 && validar!=53
        && validar!=54 && validar!=55
        && validar!=56 && validar!=57
        && validar!=127 && validar!=8
        && validar!=46)
        {
            getToolkit().beep();
            evt.consume();
        }
    }
// </editor-fold> 
    
    private void guardar(){
        if(verificarTextoNotas()){
            if(verificarNotas()){
                if(cambiarNotas.cambiarNotas(""+notaUno, 
                ""+notaDos, ""+notaTres, 
                textoObservaciones.getText(), documento, documentoDocente)){
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(rootPane, "NOTAS CAMBIADAS","EXITO",JOptionPane.INFORMATION_MESSAGE);
                    new MostrarNotasRegistradas(documentoDocente).setVisible(true);
                    this.dispose();
                }
            }else{
                getToolkit().beep();
                JOptionPane.showMessageDialog(rootPane, "VERIFIQUE QUE LAS NOTAS INGRESADAS SON CORRECTAS","NOTA INVALIDA",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "DEBE DILIGENCIAR TODAS LAS CASILLAS","INVALIDO",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void llenar(){
        textoNombre.setText(new BuscarPersona().buscarNombreEstudiante(documento));
        textoNotaUno.setText(cambiarNotas.getNotaUno());
        textoNotaDos.setText(cambiarNotas.getNotaDos());
        textoNotaTres.setText(cambiarNotas.getNotaTres());
        textoObservaciones.setText(cambiarNotas.getObservaciones());
    }
    private boolean verificarNotas(){
        
        try{
            notaUno = Float.parseFloat(textoNotaUno.getText());
            notaDos = Float.parseFloat(textoNotaDos.getText());
            notaTres = Float.parseFloat(textoNotaTres.getText());
            if(notaUno>5 || notaDos>5 || notaTres>5)
            {
                return false;
            }
        }catch(Exception e){
            return false;
        }
        return true;
    }
    private boolean verificarTextoNotas(){
        if(textoNotaUno.getText().equals("") 
        || textoNotaDos.getText().equals("") 
        || textoNotaTres.getText().equals("")
        || textoObservaciones.getText().equals(""))
        {
            return false;
        }
        return true;
    }
    private void limpiar(){
        textoNotaUno.setText("");
        textoNotaDos.setText("");
        textoNotaTres.setText("");
        textoObservaciones.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel textoMateria;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JTextField textoNotaDos;
    private javax.swing.JTextField textoNotaTres;
    private javax.swing.JTextField textoNotaUno;
    private javax.swing.JEditorPane textoObservaciones;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables
}
