/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDocente;

import Datos.*;
import Datos.Estudiante;
import Procesos.BuscarPersona;
import Procesos.ManejarArchivos;
import Procesos.MostrarNotas;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IVÁN UTRIA
 */
public class RegistrarNotas extends javax.swing.JFrame {

    ArrayList<Estudiante> lista;
    
    ManejarArchivos archivos;
    ArrayList<NotasEstudiante> listaNotas;
    
    String documentoDocente;
    
    float notaUno=0;
    float notaDos=0;
    float notaTres=0;
    
    public RegistrarNotas(){
        initComponents();
    }
    public RegistrarNotas(String documentoDocente){
        initComponents();
        textoMateria.setText(new BuscarPersona().buscarNombreMateria(documentoDocente));
        this.documentoDocente = documentoDocente;
        
        archivos = new ManejarArchivos();
        listaNotas = new ArrayList<>();
        
        llenarcombo();
        cargarNotas();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        textoMateria = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        comboListaEstudiante = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();
        comboFiltroGrado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        textoNotaTres = new javax.swing.JTextField();
        textoNotaUno = new javax.swing.JTextField();
        textoNotaDos = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoObservaciones = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();
        textoTitulo = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COLEGIO PROGRAMARTE");
        getContentPane().setLayout(null);

        textoMateria.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        textoMateria.setForeground(new java.awt.Color(255, 255, 255));
        textoMateria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoMateria.setText("ADMINISTRADOR");
        getContentPane().add(textoMateria);
        textoMateria.setBounds(580, 460, 200, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 460, 260, 30);

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png"))); // NOI18N
        botonAtras.setToolTipText("Atras");
        botonAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonAtrasMouseMoved(evt);
            }
        });
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras);
        botonAtras.setBounds(10, 10, 40, 40);

        comboListaEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListaEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(comboListaEstudiante);
        comboListaEstudiante.setBounds(220, 100, 350, 40);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("FILTRO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 70, 110, 14);

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOCUMENTO", "NOMBRE" }));
        comboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(comboFiltro);
        comboFiltro.setBounds(280, 60, 170, 30);

        comboFiltroGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "6", "7", "8", "9", "10", "11" }));
        comboFiltroGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltroGradoActionPerformed(evt);
            }
        });
        getContentPane().add(comboFiltroGrado);
        comboFiltroGrado.setBounds(460, 60, 110, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOTA3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 190, 100, 20);

        textoNotaTres.setBackground(new java.awt.Color(0, 51, 102));
        textoNotaTres.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoNotaTres.setForeground(new java.awt.Color(255, 255, 255));
        textoNotaTres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNotaTres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoNotaTres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNotaTresKeyTyped(evt);
            }
        });
        getContentPane().add(textoNotaTres);
        textoNotaTres.setBounds(470, 150, 100, 40);

        textoNotaUno.setBackground(new java.awt.Color(0, 51, 102));
        textoNotaUno.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoNotaUno.setForeground(new java.awt.Color(255, 255, 255));
        textoNotaUno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNotaUno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoNotaUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNotaUnoKeyTyped(evt);
            }
        });
        getContentPane().add(textoNotaUno);
        textoNotaUno.setBounds(220, 150, 100, 40);

        textoNotaDos.setBackground(new java.awt.Color(0, 51, 102));
        textoNotaDos.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoNotaDos.setForeground(new java.awt.Color(255, 255, 255));
        textoNotaDos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNotaDos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        textoNotaDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNotaDosKeyTyped(evt);
            }
        });
        getContentPane().add(textoNotaDos);
        textoNotaDos.setBounds(350, 150, 100, 40);

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAceptar.png"))); // NOI18N
        botonGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonGuardarMouseMoved(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(220, 370, 170, 40);

        botonMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonMostrar.png"))); // NOI18N
        botonMostrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        botonMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMostrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonMostrarMouseMoved(evt);
            }
        });
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrar);
        botonMostrar.setBounds(400, 370, 170, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOTA1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 190, 90, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("OBSERVACIONES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 340, 350, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NOTA2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 190, 100, 20);

        textoObservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));
        textoObservaciones.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        textoObservaciones.setForeground(new java.awt.Color(0, 51, 102));
        textoObservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoObservacionesKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(textoObservaciones);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 210, 350, 130);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INICIO / REGISTRAR NOTAS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 430, 780, 14);

        textoTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoTitulo.setText("REGISTRAR NOTAS");
        getContentPane().add(textoTitulo);
        textoTitulo.setBounds(490, 10, 300, 40);

        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png"))); // NOI18N
        BotonInicio.setToolTipText("Regresar al Inico");
        BotonInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonInicioMouseMoved(evt);
            }
        });
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInicio);
        BotonInicio.setBounds(60, 10, 43, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // <editor-fold defaultstate="collapsed" desc="ACCION BOTONES">
    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        InicioDocente mostrar = new InicioDocente(documentoDocente);
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed
    
    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtras.png")));
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicio.png")));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAceptar.png")));
        botonMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonMostrar.png")));
    }//GEN-LAST:event_jLabel3MouseMoved

    private void botonAtrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseMoved
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAtrasDos.png")));
    }//GEN-LAST:event_botonAtrasMouseMoved

    private void comboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroActionPerformed
        comboListaEstudiante.removeAllItems();
        llenarcombo();
    }//GEN-LAST:event_comboFiltroActionPerformed

    private void comboFiltroGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroGradoActionPerformed
        comboListaEstudiante.removeAllItems();
        llenarcombo();
    }//GEN-LAST:event_comboFiltroGradoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textoNotaUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNotaUnoKeyTyped
        if(textoNotaUno.getText().equals("") && evt.getKeyChar()==46){
            getToolkit().beep();
            evt.consume();
        }
        impedirNumeros(evt);
    }//GEN-LAST:event_textoNotaUnoKeyTyped

    private void textoNotaDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNotaDosKeyTyped
        if(textoNotaDos.getText().equals("") && evt.getKeyChar()==46){
            getToolkit().beep();
            evt.consume();
        }
        impedirNumeros(evt);
    }//GEN-LAST:event_textoNotaDosKeyTyped

    private void textoNotaTresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNotaTresKeyTyped
        if(textoNotaTres.getText().equals("") && evt.getKeyChar()==46){
            getToolkit().beep();
            evt.consume();
        }
        impedirNumeros(evt);
    }//GEN-LAST:event_textoNotaTresKeyTyped

    private void textoObservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoObservacionesKeyTyped
    }//GEN-LAST:event_textoObservacionesKeyTyped

    private void comboListaEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListaEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboListaEstudianteActionPerformed

    private void botonGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseMoved
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAceptarDos.png")));
    }//GEN-LAST:event_botonGuardarMouseMoved

    private void botonMostrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMostrarMouseMoved
       botonMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonMostrarDos.png")));
    }//GEN-LAST:event_botonMostrarMouseMoved

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        MostrarNotasRegistradas mostrar = new MostrarNotasRegistradas(documentoDocente);
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void BotonInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseMoved
        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonInicioDos.png")));
    }//GEN-LAST:event_BotonInicioMouseMoved

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        new InicioDocente(documentoDocente).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonInicioActionPerformed
    private void impedirNumeros(java.awt.event.KeyEvent evt){
        char validar = evt.getKeyChar();
        
        if(validar!=48 && validar!=49 && validar!=50 
        && validar!=51 && validar!=52 && validar!=53
        && validar!=54 && validar!=55
        && validar!=56 && validar!=57
        && validar!=127 && validar!=8
        && validar!=46)
        {
            getToolkit().beep();
            evt.consume();
        }
    }
// </editor-fold> 
    
    private void cargarNotas(){
        listaNotas = (ArrayList<NotasEstudiante>)archivos.leerNotas();
    }
    
    private void llenarcombo(){
        comboListaEstudiante.addItem("SELECCIONE");
        lista = (ArrayList<Estudiante>)archivos.leerListaEstudiante();
        for(Estudiante estudiante:lista){
            if(comboFiltroGrado.getSelectedItem().equals("TODOS")){
                if(comboFiltro.getSelectedItem().toString().trim().equals("DOCUMENTO")){
                    comboListaEstudiante.addItem(estudiante.getDocumento());
                }
                else{
                    if(comboFiltro.getSelectedItem().toString().trim().equals("NOMBRE"))
                    comboListaEstudiante.addItem(estudiante.getNombre());
                }
            }
            else{
                if(comboFiltroGrado.getSelectedItem().equals(estudiante.getGrado())){
                    if(comboFiltro.getSelectedItem().toString().trim().equals("DOCUMENTO")){
                        comboListaEstudiante.addItem(estudiante.getDocumento());
                    }
                    else{
                        if(comboFiltro.getSelectedItem().toString().trim().equals("NOMBRE"))
                        comboListaEstudiante.addItem(estudiante.getNombre());
                    }
                }
            }
        }
    }
    
    private void guardar(){
        String grado;
        String documento = null;
        String nombre = comboListaEstudiante.getSelectedItem().toString();
        listaNotas = (ArrayList<NotasEstudiante>)archivos.leerNotas();
        NotasEstudiante notas = new NotasEstudiante();
        for(Estudiante estudiante:lista){
                if(estudiante.getNombre().equals(nombre)){
                nombre = estudiante.getNombre();
                grado = estudiante.getGrado();
            }
        }
        if(comboFiltro.getSelectedItem().toString().trim().equals("DOCUMENTO")){
            documento = comboListaEstudiante.getSelectedItem().toString().trim();
        }
        else{
            
            documento = new BuscarPersona().buscarDocumento(nombre);
                
        }
        
        if(comboListaEstudiante.getSelectedItem().toString()!="SELECCIONE"){
            if(verificarRegistro()==false){
                if(verificarTextoNotas()){
                    if(verificarNotas()==true){
                        notas.setDocumento(documento);
                        notas.setDocente(documentoDocente);
                        notas.setNotaUno(""+notaUno);
                        notas.setNotaDos(""+notaDos);
                        notas.setNotaTres(""+notaTres);
                        notas.setObservaciones(textoObservaciones.getText());
                        listaNotas.add(notas);
                        archivos.GuardarNotas(listaNotas);
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(rootPane, "SE HAN REGISTRADO LAS NOTAS CORRECTAMENTE","EXITO",JOptionPane.INFORMATION_MESSAGE);
                        limpiar();
                    }else{
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(rootPane, "VERIFIQUE QUE LAS NOTAS INGRESADAS SON CORRECTAS","NOTA INVALIDA",JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(rootPane, "DEBE DILIGENCIAR TODAS LAS CASILLAS","INVALIDO",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(rootPane, "USTED HA REGISTRADO LAS NOTAS DE ESTE ESTUDIANTE","INVALIDO",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "DEBE SELECCIONAR EL ESTUDIANTE","INVALIDO",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean verificarRegistro(){
        listaNotas = (ArrayList<NotasEstudiante>)archivos.leerNotas();
        for(NotasEstudiante notas : listaNotas){
            if(notas.getDocente().equals(documentoDocente) && notas.getDocumento().equals(comboListaEstudiante.getSelectedItem().toString())){
                return true;
            }
        }
        return false;
    }
    
    private boolean verificarNotas(){
        
        try{
            notaUno = Float.parseFloat(textoNotaUno.getText());
            notaDos = Float.parseFloat(textoNotaDos.getText());
            notaTres = Float.parseFloat(textoNotaTres.getText());
            if(notaUno>5 || notaDos>5 || notaTres>5)
            {
                return false;
            }
        }catch(Exception e){
            return false;
        }
        return true;
    }
    private boolean verificarTextoNotas(){
        if(textoNotaUno.getText().equals("") 
        || textoNotaDos.getText().equals("") 
        || textoNotaTres.getText().equals("")
        || textoObservaciones.getText().equals(""))
        {
            return false;
        }
        return true;
    }
    private void limpiar(){
        comboFiltro.setSelectedItem("DOCUMENTO");
        comboFiltroGrado.setSelectedItem("TODOS");
        textoNotaUno.setText("");
        textoNotaDos.setText("");
        textoNotaTres.setText("");
        textoObservaciones.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JComboBox<String> comboFiltroGrado;
    private javax.swing.JComboBox<String> comboListaEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel textoMateria;
    private javax.swing.JTextField textoNotaDos;
    private javax.swing.JTextField textoNotaTres;
    private javax.swing.JTextField textoNotaUno;
    private javax.swing.JEditorPane textoObservaciones;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables
}
